# Concepts

## data.table vs DT

The `data.table` package is a powerful R package for data manipulation and aggregation, known for its speed and efficiency with large datasets. It provides an enhanced version of data frames with additional features like fast grouping, indexing, and in-place updates.\
On the other hand, `DT` is an R package that provides an interface to the JavaScript library DataTables. It is primarily used for creating interactive tables in R Markdown documents and Shiny applications. `DT` allows users to create sortable, searchable, and paginated tables with ease, enhancing the user experience when working with tabular data in web applications.

#### for a quarto document and output as a website, use DT for a data table.

## Link to kaggle datasets to downloaded data directly into R using the kaggle API

library(RKaggle) \# for interacting with Kaggle API)\
using RKaggle to download the dataset from Kaggle\
Example:\
superstore_dataset \<- get_dataset("vivek468/superstore-dataset-final")

github for RKaggle:\
https://github.com/benyamindsmith/RKaggle

## Leaflet

The `leaflet` package in R is a powerful tool for creating interactive maps. It allows users to visualize spatial data with various layers, markers, and pop-ups. The package is built on top of the Leaflet JavaScript library, providing a user-friendly interface for R users to create dynamic maps that can be embedded in R Markdown documents, Shiny applications, or viewed in RStudio. With `leaflet`, users can easily add tiles, polygons, and other geographical features to their maps, making it a versatile choice for geospatial data visualization.

https://rstudio.github.io/leaflet/index.html\
https://r-charts.com/spatial/interactive-maps-leaflet/\
https://r-graph-gallery.com/package/leaflet.html\
https://bookdown.org/nicohahn/making_maps_with_r5/docs/leaflet.html https://leafletjs.com/reference.html\
https://www.geeksforgeeks.org/r-language/leaflet-package-in-r/\
https://www.jla-data.net/eng/leaflet-in-r-tips-and-tricks/

## Publishing

<https://quarto.org/docs/publishing/quarto-pub.html>\
<https://quarto.org/docs/publishing/>
